### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cbardini**

### CODE REVIEW

**Review by kelseyduffy — APPROVED** [review]

**Review by derekendres — COMMENTED** [review]
For this one have we check with Joe?  They typically send us a copy of what to post and we post it.  If we edit here and its not changed there, then next release we will revert this and not know it.

**Comment by dcbroad3** [comment]
> 
> 
> For this one have we check with Joe? They typically send us a copy of what to post and we post it. If we edit here and its not changed there, then next release we will revert this and not know it.

@cbardini @derekendres I imagine this is also relevant to the README PR we already merged in [sample-pi_core-pi_core_deployment-on_prem](https://github.com/osisoft/sample-pi_core-pi_core_deployment-on_prem), right?

**Comment by cbardini** [comment]
@dcbroad3 @derekendres Should I include him as a reviewer or just reach out to him to ask?

**Comment by derekendres** [comment]
@cbardini  reach out and ask

**Review by derekendres — APPROVED** [review]

**Pull request merged**
